name: Publish

on:
  push:
    tags:
      - 'v*.*.*'
      - '*@*.*.*'
      - '@*/*@*.*.*'
  workflow_dispatch:  # Allows manual triggering for testing

jobs:
  publish:
    name: Publish ATP Ecosystem to NPM
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for provenance data generation
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: Enable Corepack
        run: corepack enable
        shell: bash

      - name: Setup Yarn
        run: corepack prepare yarn@stable --activate
        shell: bash

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache yarn dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-


      - name: Install dependencies
        run: yarn install --immutable
        shell: bash

      - name: Print Environment Info
        run: yarn nx report
        shell: bash

      - name: Build affected packages
        run: yarn build
        shell: bash

      - name: Check for publishable changes
        run: yarn nx release version --dry-run
        shell: bash

      - name: Publish packages
        run: yarn nx release publish
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_CONFIG_PROVENANCE: true